### PR TITLE
Remove sensors.yaml and inputs.yaml

### PR DESCRIPTION
**Pull request by abichinger**
#10

### CODE REVIEW

**Comment by nliaudat** [comment]
not needed anymore as fixed in commit 11386e0

**Comment by nliaudat** [comment]
Sry, I come from job now and haven't read all the commit
Very sorry cause it's seems to fix many things.

**Comment by abichinger** [comment]
Hello, I just commited these changes a few minutes ago. I should have used a new branch.

**Comment by nliaudat** [comment]
Sorry, it's my fault. I only considered the title "Remove sensors.yaml and inputs.yaml" without looking further. 

I'm going to make you a contributor so you can merge your commits directly. 

I have to admit that I don't have much time at the moment and I apologise for that.

Thanks again for your efforts!

**Pull request merged**
